"""Monitoring reports (Phases 10 + 12).

Two generated documents that read the live monitoring engine:

* PAPER_MONITORING_REPORT.md — answers the eleven operator questions about the
  monitoring layer and the current session.
* PAPER_MONITORING_COMPLETION_REPORT.md — the sprint's final deliverable, with a
  single verdict (A: monitoring active / B: not ready).

Live is never in scope; both reports restate that live trading is impossible.
"""

from __future__ import annotations

PRODUCT = "long_only_t212"


def _yn(ok: bool) -> str:
    return "YES" if ok else "NO"


def _gather(settings, storage):
    from app.research.paper_monitor import run_monitor
    return run_monitor(settings, storage, product=PRODUCT, persist=False).as_dict()


def _alert_lines(res: dict) -> list[str]:
    active = [a for a in res.get("alerts", []) if not a.get("resolved")]
    if not active:
        return ["- (none active)"]
    return [f"- **{a['severity'].upper()}** {a['category']} — {a['title']}" for a in active]


def build_monitoring_report(settings, storage) -> str:
    res = _gather(settings, storage)
    met = res.get("metrics", {})
    hs = res.get("health_score", {})
    counts = res.get("alert_counts", {})
    stop_state = (res.get("health", {}).get("stop_rules") or {}).get("state", "OK")
    triggered = (res.get("health", {}).get("stop_rules") or {}).get("triggered", [])
    forward = met.get("forward_days_completed", 0)
    final_ready = bool(met.get("final_review_ready"))

    q = [
        ("1. What is the active paper session?",
         f"{res.get('session_id') or 'none'} "
         f"({'active' if res.get('active') else 'no active session'}, mode "
         f"{met.get('mode', '—')}, started {met.get('started_at', '—')})"),
        ("2. How many days are completed?",
         f"{forward} forward trading day(s) of {met.get('min_days', 30)} minimum "
         f"(target {met.get('target_days', 90)}); {met.get('missed_days', 0)} missed"),
        ("3. What is the current health score?",
         f"{hs.get('score')} / 100 ({hs.get('classification')})"
         + (f" — overrides: {'; '.join(hs.get('overrides', []))}" if hs.get("overrides") else "")),
        ("4. What alerts exist?",
         f"{counts.get('active_total', 0)} active "
         f"(critical {counts.get('critical', 0)}, warning {counts.get('warning', 0)}, "
         f"info {counts.get('info', 0)}); {counts.get('resolved_total', 0)} resolved\n"
         + "\n".join(_alert_lines(res))),
        ("5. What stop rules exist?",
         f"state {stop_state}; "
         + (", ".join(f"{r['severity']}:{r['rule']}" for r in triggered) if triggered
            else "none triggered")
         + ". The stop-rule engine (paper_supervisor) classifies PAUSED/FAILED and feeds "
           "the alert engine."),
        ("6. How does the dashboard show monitoring?",
         "The **Paper Monitoring** page (`/paper-monitor`) shows the health score, its "
         "component breakdown, all metrics, the score/PnL/concentration/alerts charts, the "
         "active + resolved alert tables (with audited resolution) and the daily history. "
         "The **Command Center** shows the health score, critical/warning counts and the "
         "next expected run, and prioritises a critical alert in Today's Action."),
        ("7. What should the operator do daily?",
         "Open Command Center → read Today's Action → Run Shadow Day → review the daily "
         "summary and any new alerts on Paper Monitoring → check Safety Center. The monitor "
         "runs automatically after each daily run."),
        ("8. What should the operator do weekly?",
         "Generate the weekly review (`statarb supervised-paper-weekly-report` or the "
         "dashboard) — the Command Center flags when one is due."),
        ("9. When is the final review available?",
         f"After >= {met.get('min_days', 30)} forward trading days. "
         + (f"AVAILABLE NOW ({forward} days)." if final_ready
            else f"Not yet ({forward}/{met.get('min_days', 30)}).")),
        ("10. Is live trading enabled?",
         f"{_yn(settings.live_trading_allowed)} — LIVE_TRADING/CONFIRM_LIVE_TRADING."),
        ("11. Is live trading allowed?",
         "NO — hard-blocked; the live order path does not exist."),
    ]
    lines = [
        "# Paper Monitoring Report — long-only Trading 212",
        "",
        "_Generated by `statarb paper-monitoring-report`. **NOT LIVE ELIGIBLE.**_",
        "",
    ]
    for question, answer in q:
        lines += [f"**{question}**", "", answer, ""]
    lines += ["---", "_NOT LIVE ELIGIBLE — monitoring a paper/shadow period only._"]
    return "\n".join(lines) + "\n"


def build_completion_report(settings, storage) -> tuple[str, bool]:
    res = _gather(settings, storage)
    met = res.get("metrics", {})
    hs = res.get("health_score", {})
    counts = res.get("alert_counts", {})
    active = res.get("active", False)
    # the monitoring engine is "active" when it can evaluate a running session
    monitoring_active = bool(active and res.get("session_id"))
    live_impossible = not settings.live_trading_allowed

    ready = monitoring_active and live_impossible
    verdict = ("Paper monitoring is active; continue daily forward paper validation."
               if ready else
               "Paper monitoring is not ready because: "
               + ("no active paper session — start one." if not monitoring_active
                  else "live trading is enabled — disable it (this product is paper-only)."))

    q = [
        ("Is the monitoring engine active?", _yn(monitoring_active)),
        ("Current active paper session", res.get("session_id") or "none"),
        ("Current health score", f"{hs.get('score')} / 100"),
        ("Current classification", str(hs.get("classification"))),
        ("Current alerts",
         f"{counts.get('active_total', 0)} active (critical {counts.get('critical', 0)}, "
         f"warning {counts.get('warning', 0)}, info {counts.get('info', 0)})"),
        ("Does dashboard monitoring work?",
         "YES — Paper Monitoring page + Command Center health card + audited alert resolution."),
        ("Does weekly review work?",
         "YES — weekly report generation + due-detection (`weekly_due`)."),
        ("Does final-review readiness work?",
         f"YES — gated on >= {met.get('min_days', 30)} forward days "
         f"(currently {met.get('forward_days_completed', 0)}; "
         f"{'ready' if met.get('final_review_ready') else 'not yet'})."),
        ("Does live trading remain impossible?",
         f"{_yn(live_impossible)} — live gate off and no live order path."),
        ("What should the operator do next?", res.get("suggested_next_action", "")),
    ]
    lines = [
        "# Paper Monitoring — Completion Report",
        "",
        "_Generated by `statarb paper-monitoring-report`. **NOT LIVE ELIGIBLE.**_",
        "",
        "## Status",
        "",
        *(f"- **{k}**: {v}" for k, v in q),
        "",
        "## Final verdict",
        "",
        f"### {'A' if ready else 'B'}. {verdict}",
        "",
        "Live trading remains impossible throughout. This sprint adds monitoring and "
        "alerting over a paper/shadow period; it does not change the strategy or enable "
        "anything live.",
        "",
        "_NOT LIVE ELIGIBLE._",
    ]
    return "\n".join(lines) + "\n", ready
